### ISSUE TITLE
Source Maps Url Problem

### ISSUE THREAD

**Issue by mickeyvip** [google/traceur-compiler#1685]
The source maps url is absolute with root of the (`/Users/username/...`) machine, so it does not work in the browser.

Seems like the issue started since v0.8.x

**Comment by johnjbarton** [comment]
See #1676

**Comment by mickeyvip** [comment]
I saw the commits for `v0.0.82`-`v0.0.84` and the closed issues.

What was the change? I don't see anything changing if I set different `--source-root`:

```bash
$ ./node_modules/traceur/traceur -v
0.0.84
```
1. Not setting Source Root
```bash
$ ./node_modules/.bin/traceur --source-maps --out=./dist/js/bundle.js ./src/js/app.js"
> traceur-test@1.0.0 build /Users/me/Projects/nodejs/traceur-test
> traceur --source-maps --out ./dist/js/bundle.js ./src/js/app.js
```
`bundle.js`:
```javascript
// ...
//# sourceMappingURL=/Users/me/Projects/nodejs/traceur-test/dist/js/bundle.map
```

2. Setting Source Root to `false`
```bash
$ ./node_modules/.bin/traceur --source-maps --source-roor false --out=./dist/js/bundle.js ./src/js/app.js"
> traceur-test@1.0.0 build /Users/me/Projects/nodejs/traceur-test
> traceur --source-maps --source-root false --out ./dist/js/bundle.js ./src/js/app.js
```
`bundle.js`:
```javascript
// ...
//# sourceMappingURL=/Users/me/Projects/nodejs/traceur-test/dist/js/bundle.map
```

3. Setting Source Root to `true`
```bash
$ ./node_modules/.bin/traceur --source-maps --source-roor true --out=./dist/js/bundle.js ./src/js/app.js"
> traceur-test@1.0.0 build /Users/me/Projects/nodejs/traceur-test
> traceur --source-maps --source-root true --out ./dist/js/bundle.js ./src/js/app.js
```
`bundle.js`:
```javascript
// ...
//# sourceMappingURL=/Users/me/Projects/nodejs/traceur-test/dist/js/bundle.map
```

4. Setting Source Root to `http://www.example.com/`
```bash
$ ./node_modules/.bin/traceur --source-maps --source-roor true --out=./dist/js/bundle.js ./src/js/app.js"
> traceur-test@1.0.0 build /Users/me/Projects/nodejs/traceur-test
> traceur --source-maps --source-root  http://www.example.com --out ./dist/js/bundle.js ./src/js/app.js
```
`bundle.js`:
```javascript
// ...
//# sourceMappingURL=/Users/me/Projects/nodejs/traceur-test/dist/js/bundle.map
```

In all cases the output is the same - absolute path, which browser cannot find.

So what has changed?

**Comment by johnjbarton** [comment]
The --source-root has no effect on the value of the sourceMappingURL

**Comment by johnjbarton** [comment]
What is it that you want to happen?

Does your output have a `//# sourceURL`? If yes, what is its value?

**Comment by mickeyvip** [comment]
Hi.

I am expecting my browser to be able to pick up the correct `bundle.map` location and load it. Then to know the  correct `urls` of the source files and be able to load them.

Currently it tries to load `map` file from `/Users/me/Projects/nodejs/traceur-test/dist/js/bundle.map`.

No, the `bundle.js` has only
`//# sourceMappingURL=/Users/me/Projects/nodejs/traceur-test/dist/js/bundle.map`.

Also I see another thing that may be generated wrong.

My folder structure:
```
\--traceur-test
   \--dist
   |   \--js
   |      |--bungle.js
   |      |--bindle.map
   \--src
   |   \--js
   |      |--app.js
   |      |--greeter.js
   |--package.json
```

in my `package.json` I have:
```json
{
  "scripts": {
    "build": "./node_modules/.bin/traceur --source-maps --source-root=false --out ./dist/js/bundle.js ./src/js/app.js"
  }
}
```
(it's `--source-root=false` here, but as I pointed before I have tried all the options)

Running `npm run build` produces the `/dist/js/bundle.js` and `/dist/js/bunde.map`. Now the last line of `bundle.js` is:
```javascript
//# sourceMappingURL=/Users/me/Projects/nodejs/traceur-test/dist/js/bundle.map
```
wich is not good for the browser. I have chaged it manually to:
```javascript
//# sourceMappingURL=bundle.map
```
Now I see `bundle.map` is loaded into the browser, but the source files' paths are incorrect. Actually the `bundle.map` looks like this:
```json
{
  "version": 3,
  "sources": [
    "@traceur/generated/TemplateParser/6",
    "@traceur/generated/TemplateParser/5",
    "@traceur/generated/TemplateParser/4",
    "@traceur/generated/TemplateParser/7",
    "../src/greeter.js",
    "@traceur/generated/TemplateParser/8",
    "@traceur/generated/TemplateParser/1",
    "@traceur/generated/TemplateParser/3",
    "@traceur/generated/TemplateParser/2",
    "../src/app.js",
    "@traceur/generated/TemplateParser/9",
    "@traceur/generated/TemplateParser/10",
    "@traceur/generated/TemplateParser/11"
  ],
  "names": [],
  "mappings": "AAAA,KAAK,eAAe,AAAC,2BAAoB,GAAC,CCA1C,UAAS,AAAD;;ACAR,AAAI,IAAA,CAAA,YAAW,4BAAoB,CAAC;ACApC,AAAI,IAAA,UCAW,SAAM,QAAM,KAI3B,ADJwC,CAAA;AEAxC,EAAC,eAAc,YAAY,CAAC,AAAC,WDC3B,KAAI,CAAJ,UAAM,AAAiB,CAAG;QAApB,KAAG,6CAAI,YAAU;AACrB,YAAM,IAAI,AAAC,EAAC,KAAK,EAAC,KAAG,EAAC,IAAE,EAAC,CAAC;IAC5B,MCHmF;ACArF,AAAI,IAAA,CAAA,UAAS,UAAoB,CAAA;ACAjC,SCAA,aAAwB;AAAE,uBAAwB;IAAE,EDA7B;ANEjB,CDFwD,CAAC;AAA/D,KAAK,eAAe,AAAC,uBAAoB,GAAC,CCA1C,UAAS,AAAD;;ACAR,AAAI,IAAA,CAAA,YAAW,wBAAoB,CAAC;IOA7B,QAAM,ECAb,CAAA,MAAK,IAAI,AAAC,2BAAkB;ADE5B,AAAI,IAAA,CAAA,OAAM,EAAI,IAAI,QAAM,AAAC,EAAC,CAAC;AAC3B,QAAM,MAAM,AAAC,EAAC,CAAC;AEHf,AAAI,IAAA,CAAA,UAAS,EFKE,GAAC,AELiB,CAAA;AJAjC,SCAA,aAAwB;AAAE,uBAAwB;IAAE,EDA7B;ANEjB,CDFwD,CAAC;AYA/D,KAAK,IAAI,AAAC,CAAC,uBAAmB,GAAC,CAAC,CAAA",
  "file": "/Users/me/Projects/nodejs/traceur-test/dist/js/bundle.js",
  "sourcesContent": [
    "System.registerModule($__placeholder__0, [], $__placeholder__1);",
    "function() {\n        $__placeholder__0\n      }",
    "var __moduleName = $__placeholder__0;",
    "var $__placeholder__0 = $__placeholder__1",
    null,
    "($traceurRuntime.createClass)($__placeholder__0, $__placeholder__1, $__placeholder__2)",
    "var $__default = $__placeholder__0",
    "return $__placeholder__0",
    "get $__placeholder__0() { return $__placeholder__1; }",
    null,
    "System.get($__placeholder__0)",
    "var $__default = $__placeholder__0",
    "System.get($__placeholder__0 +'')"
  ]
}
```
I have noticed that `sources` key has incorrect source paths (`"../src/greeter.js"`, ` "../src/app.js"`). There is no `/js` in both of them (a bug?), so for any `sourceRoot` those sources could not be found.

For the sake of exhaustive tests here are the values of the `sourceRoot` and `sources`'s paths (omitting the `"@traceur/generated/TemplateParser/xx"` ones):

1. `--source-root=true`: `"sourceRoot": "/Users/me/Projects/nodejs/traceur-test/dist/js/"`, `["../src/greeter.js", "../src/app.js"]`

2. `--source-root=/`: `"sourceRoot": "/"`, `["../src/greeter.js", "../src/app.js"]`

2. `--source-root=http://localhost:8080/`: `"sourceRoot": "http://localhost:8080/"`, `["../src/greeter.js", "../src/app.js"]`

**Comment by johnjbarton** [comment]
Does your output have a //# sourceURL? If yes, what is its value?

**Comment by mickeyvip** [comment]
I have answered this in my previous long comment:

No, the `bundle.js` has only
```javascript
//# sourceMappingURL=/Users/me/Projects/nodejs/traceur-test/dist/js/bundle.map.
```

By "output" do you mean `.js`? `.map`? both?

**Comment by johnjbarton** [comment]
Sorry, I meant the .js output.

**Comment by johnjbarton** [comment]
Maybe `--out <file>` is being resolved before we use it to create the sourceMappingURL.  Let me look into that.

**Comment by pflannery** [comment]
I have the same problem too. I'm having to amend the generated js file at the bottom
from this:
```js
//# sourceMappingURL=d:/some/absolute/path/dist/some.map
```
to this
```js
//# sourceMappingURL=some.map
```

otherwise the browser tries to resolve ```http://someurl/d:/some/absolute/path/dist/some.map```

**Comment by mickeyvip** [comment]
@johnjbarton, thank you.

@pflannery , this is the 1st part of the problem (in my case anyway).

The 2nd one is that the browser cannot load sources because the paths to them seem to be corrupted - instead of being `/src/js/app.js` they become `../src/app.js` (the `js` is lost).

Are you experiencing the same?

Thanks

**Comment by pflannery** [comment]
my structure is a bit different

```
\--app
   \--dist
   |   |--myapp.js
   |   |--myapp.map
   \--src
   |   |--myapp.js
   |   \--utils
   |      |--myutil.js
   |--package.json
```

so ```../src/app.js``` works well for me and I can step through the es6 source :)

**Comment by johnjbarton** [comment]
@mickeyvip I really don't understand how that `/js` can go missing.

The sourceMappingURL really needs to be relative.

**Comment by mickeyvip** [comment]
@johnjbarton, it is missing, I copy-pasted the generated code.

I am on Mac. I can send you my project files.

**Comment by johnjbarton** [comment]
I think you posted enough to reproduce your issue, let me try.

**Comment by johnjbarton** [comment]
I am able to reproduce these issues.

**Comment by mickeyvip** [comment]
What is this simple setup different from most people's setups that are not having those issues?

**Comment by jmm** [comment]
> @mickeyvip I really don't understand how that `/js` can go missing.

Really? `sourceName` is manipulated based on `outputName`. It sounds like the same issue as #1695.

```js
(new traceur.NodeCompiler({sourceMaps: 'inline', script: true}))
  .compile("console.log('x');", './src/js/app.js', './dist/js/bundle.js');
```

Result: `"sources":["../src/app.js"]`

**Comment by johnjbarton** [comment]
I fixed a bug and added a test based on the folder structure outlined here.   Please try it out and let me know.

**Comment by mickeyvip** [comment]
@johnjbarton , is the new version on NPM?

I just updated `traceur`, and it is still `0.0.85` and the problem still exists.

Inside `package.json` here on `GitHub` it says `0.0.86`.

**Comment by mickeyvip** [comment]
In my small example it works!

Thank you!

**Comment by mickeyvip** [comment]
What is not working is `gulp-sourcemaps` in `gulp-traceur`, which I am not sure is relevant here.
